version: "3.8"

services:
  app:
    build: .
    container_name: gosha-node
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://admin:goshaadmin123@mongo:27017/
      JWT_SECRET: gosha_secret_secret
    volumes:
      - .:/app:cached # Bind mount your code
      - node_modules:/app/node_modules # Named volume for isolated node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: goshaadmin123

volumes:
  node_modules:
